### ISSUE TITLE
TypeError: this.pc is undefined

### ISSUE THREAD

**Issue by serprex** [QuickBlox/sample-webrtc-web#2]
Line 466 of quickblox.webrtc.js. Caused because new adapter.RTCPeerConnection(pcConfig, PC_CONSTRAINTS) is failing to use google's stun server & fallback to quickblox's turnserver is apparently failing due to blank username/credential fields

Am running on Firefox 33

**Comment by tpemckiernan** [comment]
I have this issue too - any solutions?

**Comment by soulfly** [comment]
You can try to use new QuickBlox TURN server: turn.quickblox.com with username:"quickblox" password:"baccb97ba2d92d71e26eb9886da5f1e0"

**Comment by tpemckiernan** [comment]
That tip works a treat - thanks!
